# Netlify configuration file
[build]
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "/blog.html"
  status = 200
  force = false
  
[build.environment]
  # Add any environment variables here if needed

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

